### ISSUE TITLE
Release 0.1.5

### ISSUE THREAD

**Issue by romainfrancois** [echasnovski/keyholder#5]
The cran version seems to fail against dplyr 1.0.0, but it looks like the dev version is fine. Would you consider releasing before we get `dplyr` 1.0.0 out (tentatively on may 15) ?

**Comment by echasnovski** [comment]
Of course. I've been waiting for 'vctrs' and 'dplyr' to settle with all possible upcoming changes, so that I wouldn't have to reupload right away.
I'll make release this week.

**Comment by echasnovski** [comment]
Version 0.1.5 is on CRAN now.
